### ISSUE TITLE
Fama-French 48 industry - ffind

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#13]
I had a look the [source code of`ffind`](https://sites.google.com/site/judsoncaskey/data) comand. And the behavior of `ffind` has a minor difference from [FF48 industry from French data library](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/Data_Library/det_48_ind_port.html). `ffind` groups all sic codes which are not sitting in any of the 47 industries to Other (Almost Nothing) industry. 
However, FF48 defines Other industry as below:
```          
4950-4959 
4960-4961 
4970-4971 
4990-4991 
```

`ffind` includes the following sic codes in Other industry: 900, 3990, 6797, 9995, 9997. Those sic codes are not in FF48 Other industry.

For your information, two files call `ffind` command: `Stata/14_PrepareAnnualCS.do` and `Stata/30_CreateSignalsNoFilterVersion.do`.

**Comment by jacaskey** [comment]
@mk0417 you are correct regarding the industries 900, 3990, 6797, 9995, 9997. The 48-industry file on [Kenneth French's website](http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/Data_Library/changes_ind.html)  do not define these industries, at all, so the code I wrote put them in the "other" category rather than leave them unassigned to any of the industry groupings.

**Comment by OpenSourceAP** [comment]
Thanks @mk0417 @jacaskey ! I think we can leave it as is and add a note to the documentation.

**Comment by chenandrewy** [comment]
added to FAQ
