### ISSUE TITLE
zerotrade

### ISSUE THREAD

**Issue by mk0417** [OpenSourceAP/CrossSection#132]
A query about the construction of **zerotrade**,

1. For **zerotradeAlt1**, it is information from t-1
2. For **zerotrade**, the average is from t-5 to t
3. For **zerotradeAlt12**, the average is from t-12 to t-1

So 1 and 3 use information up to t-1 and 2 uses information up to t?

```stata
// 40n1 Number of days with 0 trades (1 month version)
gen zerotradeAlt1 = l.temp_zerotrade
label var zerotradeAlt1 "Days with zero trades (1 month version)"
// 40 Number of days with 0 trades (6 month version)
gen zerotrade = (temp_zerotrade + l.temp_zerotrade + l2.temp_zerotrade + l3.temp_zerotrade + ///
    l4.temp_zerotrade + l5.temp_zerotrade)/6

label var zerotrade "Days with zero trades (6 month version)"

// 40n12 Number of days with 0 trades (12 month version)
gen zerotradeAlt12 = (zerotradeAlt1 + l.zerotradeAlt1 + l2.zerotradeAlt1 + l3.zerotradeAlt1 + ///
    l4.zerotradeAlt1 + l5.zerotradeAlt1 + l6.zerotradeAlt1 + l7.zerotradeAlt1 + l8.zerotradeAlt1 + ///
    l9.zerotradeAlt1 + l10.zerotradeAlt1 + l11.zerotradeAlt1)/12
label var zerotradeAlt12 "Days with zero trades (12 month version)"
```

**Comment by tomz23** [comment]
Fixed in https://github.com/OpenSourceAP/CrossSection/commit/c23dfbac99253908ae5f1b46440b970da20fddbe.

- The previous version of the zerotrade code was somewhat sloppy (beyond the lag issue) in that it computed the 6 and 12 month versions of the signal as just the average of the 1-month version. The new version computes the turnover or zero day sum over 6 or 12 months first before constructing the signal (and it uses the deflator of 11k used in the paper for those versions rather than the 480k deflator that is only used for the one-month version).
- Also updated the signal names to be more consistent:
    - `zerotrade` is now `zerotrade6M`
    - `zerotradeAlt1` is now `zerotrade1M`
    - `zerotradeAlt12` is now `zerotrade12M`
- `signaldoc.csv` reflects the updated variable names.
- There was also a typo in the documentation in that the OP 12 month version also uses deciles (as do the other versions) and not quintiles
