### ISSUE TITLE
FirmAgeMom missing values and weird code

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#136]
There's weird stuff in `FirmAgeMom.do`

There seem to be no observations of FirmAgeMom in 2021 July.

Seems to be due to this snippet
```
replace FirmAgeMom = . if abs(prc) < 5 | tempage < 12
egen temp = fastxtile(tempage), by(time_avail_m) n(5)  // Find bottom age quintile
replace FirmAgeMom =. if temp > 1 & temp !=.
```
is the `&` supposed to be `|`?  That looks weird.

Anyway, the bottom quintile of age is very small in 2021, at around 11-12:

![image](https://github.com/OpenSourceAP/CrossSection/assets/65506481/2c77dcf4-d982-4df5-b22b-9bbf6316e796)

and that seems to be interacting with the filter above and causing the gap.

**Comment by tomz23** [comment]
Fixed in https://github.com/OpenSourceAP/CrossSection/commit/6e8632115395b9c72fb6b587a03c3644b61f9a34.
Dropping obs with `abs(prc)<5) | tempage <12` and computing quantiles on the remaining stocks leads to more reasonable numbers:


![grafik](https://github.com/user-attachments/assets/99182b5b-828f-4b22-b4d4-139ad99cac26)
