### ISSUE TITLE
Typo for AgeIPO in SignalDoc

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#142]
The SampleStartYear here does not seem right:

![image](https://github.com/OpenSourceAP/CrossSection/assets/65506481/a916e653-6bdf-4a46-aa92-43ebebac4d18)

For IPOs it looks right. Table II lists dates 1975-84. But Table IX does not list dates but it also doesn't say it's using a super tiny subset as described in Signaldoc.csv.  Here's the full table: 

![image](https://github.com/OpenSourceAP/CrossSection/assets/65506481/2e10140a-2342-4427-910f-1244c9d78a98)

**Comment by tomz23** [comment]
Updated in https://github.com/OpenSourceAP/CrossSection/commit/57902573c561e4231a627c41f5a6dab77ef2b950. 

The table note says that it uses the same number of IPOs as the other tables, so sample period should be the same, too. In addition, same note as for `IndIPO` applies: Sample end year should be extended by three years since the strategy follows stocks for three years.
