### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by firmai** [OpenSourceAP/CrossSection#39]
Who is going to be the brave soul that turns this into Python code? :)

**Comment by mk0417** [comment]
I am also interested in the Python code. Is there anyone who has already started the Python version? If yes, we might make pull request and contribution there.

**Comment by Jiacheng-Liu** [comment]
I'm also interested in Python code, happy to contribute too!

**Comment by chenandrewy** [comment]
Thanks for offering to help @Jiacheng-Liu!  But, I feel a bit doubtful that we'll end up with a major Python version because of this poll:

https://twitter.com/israelsen/status/1439973179032842241

![image](https://user-images.githubusercontent.com/65506481/135920583-949b1fac-0c89-4359-9442-5684495fc14c.png)

I think a pure R version will come first, at least, since the portfolio code is in R.  Ideally the user only has to deal with installing one open source package.  

Thoughts?  @tomz23?

**Comment by tomz23** [comment]
Yep, R version is probably higher priority currently. Main challenge will be to keep implementations in different languages in sync.

**Comment by chenandrewy** [comment]
OK, I think I will close this issue then.  It seems to difficult to coordinate a Python version given that the R version is the higher priority (due to the informal poll) and difficult enough to implement.
