### ISSUE TITLE
I am witnessing a range of empty values (daily data)

### ISSUE THREAD

**Issue by firmai** [OpenSourceAP/CrossSection#44]
The Piotroski Score at the very bottom shows that for each row there is at least on portfolio value missing (null, NaN)

![image](https://user-images.githubusercontent.com/26666267/121693608-357fd100-cac1-11eb-86c1-451356bf5496.png)

![image](https://user-images.githubusercontent.com/26666267/121702126-809de200-cac9-11eb-9351-f85633b40776.png)

The PS score is the weirdest of them all:

![image](https://user-images.githubusercontent.com/26666267/121703859-21d96800-cacb-11eb-8140-2d317c2af065.png)

_Originally posted by @firmai in https://github.com/OpenSourceAP/CrossSection/issues/43#issuecomment-859581890_

**Comment by chenandrewy** [comment]
It looks like there is slight error in our computation of the Piotroski Score (PS) portfolios.  We categorize this signal as continuous-decile when it should have been discrete (ranging from 0 to 9).  We also should be going long stocks with a score of 8 or 9 and shorting stocks with a score of 0 or 1.  See caption for Table 3 of Piotroski (2000): 

![image](https://user-images.githubusercontent.com/65506481/122444218-54251280-cf6e-11eb-8856-104111f86166.png)

Gonna be honest, not sure this is a high priority thing to fix.  But we'll try to remember to fix this when we update the data next year.

**Comment by firmai** [comment]
Hi @chenandrewy thanks for the reply, I think it's a bit more systematic than that, the screenshots that I gave in the beginning also have null values, and there is a larger list of variables that also have this problem. I know how hard it is to publish something open source, it gets combed over with a fine comb, but there is something quite great in that as it will ensure that in the long run, you have the most reputable (verifiable) study on the topic - so kudos to that.

**Comment by chenandrewy** [comment]
Ah, sorry I should have looked more closely.  Yes, I think

**Comment by chenandrewy** [comment]
It turns out the missing portfolio returns for ExclExp was not due to IBES data availability.  Instead, it's because ExclExp has a big mode at 0.  Intuitively, ExclExp is "Street" aka "Non-Gaap" aka IBES earnings less GAAP earnings.  So a lot of the time there is no difference, no funny exclusions and you get a ton of zeros.  Here is the distribution of Excluded Expenses in June 1996

![image](https://user-images.githubusercontent.com/65506481/122603814-f4e50200-d042-11eb-8ec9-868e891b56bb.png)

And then when you try to sort into quintiles, you get annoying edge cases.  

In our portfolio code, we use inequality constraints on the extreme quantiles to maintain good behavior in the long-short portfolios.  In the interior portfolios, you get these edge cases.  This will be a pain for ML folks.  But for single sorting it's fine.  

Nothing to see here, unless you're an accounting nerd, but we'll ad this to the FAQ.

**Comment by chenandrewy** [comment]
We updated the FAQ to explain these missing values: 

https://www.openassetpricing.com/faq/#q-missings
