### ISSUE TITLE
asrol library needs to be set up

### ISSUE THREAD

**Issue by chenandrewy** [OpenSourceAP/CrossSection#73]
@antoniogilderubio is getting a lot of r(111) errors like these: 
![image](https://user-images.githubusercontent.com/65506481/154808510-8f08b9ca-84d9-49e3-b77b-b414a4c54995.png)
![image](https://user-images.githubusercontent.com/65506481/154808543-40cb881d-c2e4-4179-a69e-f39e45f235b5.png)
but I have no such errors when I run it.  I think an anonymous github user posted a similar issue.

I think there are about 10 in total.

Is there a way we can add the asrol setup to master.do somehow?

**Comment by tomz23** [comment]
So it seems to me that `asrol` changed automated variable naming from `StatisticLag_Varname` to `Varname_StatisticLag` in the new version. This affects all signal files that use `asrol`. I'll update those to be consistent with the new naming convention.

**Comment by tomz23** [comment]
Sigh, I received another error as well which I think is due to a version update. For example. for `DivYieldAnn.do`:

![image](https://user-images.githubusercontent.com/32535583/154979881-cf29cdfe-56dd-409c-ba87-8ed75346c03b.png)

Since, `ssc install` does not support installing specific versions of commands, I think we'll have to update to the newest version of `asrol` and understand the error above (which I currently do not do).

**Comment by tomz23** [comment]
Fixed in https://github.com/OpenSourceAP/CrossSection/commit/ca194d3bb3d0561060c3473a12abcbe0655e0e11
